apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-reverse-proxy
  template:
    metadata:
      labels:
        app: apache-reverse-proxy
    spec:
      containers:
        - name: apache-reverse-proxy
          image: sodapopin/apache-reverse-proxy:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-reverse-proxy
spec:
  type: LoadBalancer
  selector:
    app: apache-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
